### ISSUE TITLE
How to edit mask?

### ISSUE THREAD

**Issue by swagzhang** [cientgu/Mask_Guided_Portrait_Editing#1]
Hello~ Thank you for sharing such nice project. I did not find a easy find to modify mask. Would you mind plz provide mask editor if possible? Thank u in advance

**Comment by cientgu** [comment]
sorry， the tool i used comes from a data labeling company, so i am not allowed to share you, apologize for that.

**Comment by swagzhang** [comment]
Could u at least tell me which tool? so I may be able to acquire from the data labelling company.

**Comment by cientgu** [comment]
> Could u at least tell me which tool? so I may be able to acquire from the data labelling company.

plz email me at gsy777@mail.ustc.edu.cn

**Comment by Blue-Clean** [comment]
hey,thanks for your nice work! I am also wanna to edit mask.and I have a question,why the  images in datasets\helen_align\edit_label and datasets\helen_align\edit_label2 is all black in my computer?

**Comment by Blue-Clean** [comment]
@cientgu hey,thanks for your nice work! I am also wanna to edit mask.and I have a question,why the images in datasets\helen_align\edit_label and datasets\helen_align\edit_label2 is all black in my computer?

**Comment by cientgu** [comment]
> @cientgu hey,thanks for your nice work! I am also wanna to edit mask.and I have a question,why the images in datasets\helen_align\edit_label and datasets\helen_align\edit_label2 is all black in my computer?

the range of face mask label is from 0 to 10, but the range of image is 0 to 255, so it appears to be almost black, you can visiualize it by multiply a number like 20

**Comment by Blue-Clean** [comment]
@cientgu yes, I load the image and found the value is  around 10. Thank you so much！！！
