### ISSUE TITLE
Generate mask for custom images?

### ISSUE THREAD

**Issue by harsh21476** [cientgu/Mask_Guided_Portrait_Editing#3]
How do I generate mask(label) for a custom image? As of now, the masks are already given [here](https://github.com/cientgu/Mask_Guided_Portrait_Editing/tree/master/datasets/helen_edit2/editfree_label) for the example images. Thank you.

**Comment by cientgu** [comment]
Do you mean how to edit the mask? Or how to generate the groundtruth image masks?

**Comment by Harsh-machine-ai** [comment]
I mean how to generate ground-truth image masks. As of now, I am using another mask generator network to generate masks for images. Thanks

**Comment by harsh21476** [comment]
Thanks for replying. I mean how to generate ground-truth image masks. As of now, I am using another mask generator network to generate masks for images.

**Comment by cientgu** [comment]
> Thanks for replying. I mean how to generate ground-truth image masks. As of now, I am using another mask generator network to generate masks for images.

we use the method proposed in this paper "Face Parsing with RoI Tanh-Warping", some reference code and data can be found here:  [https://github.com/Eskender-B/roi-tanh] and [https://github.com/JPlin/Relabeled-HELEN-Dataset]

**Comment by weiweiecho** [comment]
@harsh21476 hi ,do you have a mask generator network that can get the mask of human face images?Could you  please provide it for me? Thanks very much!
