### ISSUE TITLE
Could you release the face parsing model PF?

### ISSUE THREAD

**Issue by xiaopi-ouo** [cientgu/Mask_Guided_Portrait_Editing#6]
I wanted to generate masks of some samples,but didn't see the PF model. Thanks

**Comment by Jessicall** [comment]
@cientgu I also want to use the model to generate the mask ,could you please provide the model?
Thank you very much!

**Comment by cientgu** [comment]
For the face parsing model, we refer to "Face Parsing with RoI Tanh-Warping" (CVPR2019) and code is here ( https://github.com/Eskender-B/roi-tanh ), please refer to this one.
